# Generated by Django 4.2.7 on 2025-11-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_todo_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='todo',
            new_name='todos_todo_created_1ddebf_idx',
            old_name='todos_todo_created_idx',
        ),
        migrations.RenameIndex(
            model_name='todo',
            new_name='todos_todo_is_fini_918d90_idx',
            old_name='todos_todo_is_fini_idx',
        ),
    ]
